export const dataArray = [
  {
    label: 'Tagline',
    value: 'Sidhant',
    type: 'input',
    name: 'Tagline',
    message: 'Enter an attractive tag line for your brand.',
  },
  {
    label: 'About',
    value: '',
    type: 'textarea',
    name: 'About Us',
    message: 'Add some description about your brand. This will help people to know you better.',
  },
  { label: 'Email', value: '', type: 'input', name: 'email' },
  { label: 'Mobile Number', value: '', type: 'input', name: 'Phone' },
  { label: 'Address', value: '', type: 'textarea', name: 'Address' },
  {
    label: 'State',
    value: '',
    type: 'select',
    name: 'State',
    data: [
      'Andaman and Nicobar Islands',
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chandigarh',
      'Chhattisgarh',
      'Dadra and Nagar Haveli',
      'Daman and Diu',
      'Delhi',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Lakshadweep',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Puducherry',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
    ],
  },
  {
    label: 'City',
    value: '',
    type: 'input',
    name: 'City',
  },

  { label: 'Facebook profile link', value: '', type: 'input', name: 'Facebook' },
  { label: 'Instagram profile link', value: '', type: 'input', name: 'Instagram' },
  { label: 'LinkedIn profile link', value: '', type: 'input', name: 'Linkedin' },
  { label: 'Telegram profile link', value: '', type: 'input', name: 'Telegram' },
  { label: 'Watsapp profile link', value: '', type: 'input', name: 'Whatsapp' },
  { label: 'Youtube profile link', value: '', type: 'input', name: 'Youtube' },
  { label: 'Other link', value: '', type: 'input', name: 'Others' },
];
